#!/usr/bin/env python3

import sys

import helpers
from analyzer import Analyzer
from termcolor import colored

def main():

    # ensure proper usage
    if len(sys.argv) != 2:
        sys.exit("Usage: ./tweets @screen_name")
        
    # instantiate analyzer
    analyzer = Analyzer()
    screen_name = (sys.argv[1]).lstrip("@")
    
    # take limeline
    tweets = helpers.get_user_timeline(screen_name, 50)
    for tweet in tweets:
        score = analyzer.analyze(tweet)
        if (score > 0.0):
            print(colored(str(score)+" "+tweet, "green"))
        elif (score < 0.0):
            print(colored(str(score)+" "+tweet, "red"))
        else:
            print(colored(str(score)+" "+tweet, "yellow"))

if __name__ == "__main__":
    main()
